### PR TITLE
r/dyn_record: Support records for top level domain

### LINKED ISSUE #6: `dyn_record` fails with records for the top level domain
_This issue was originally opened by @jbarreneche as hashicorp/terraform#11078. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
```
$ terraform -v
Terraform v0.8.2
```

### Affected Resource(s)
- dyn_record

### Terraform Configuration Files
```hcl
resource "dyn_record" "root_restorando_net" {
  zone = "restorando.net"
  name = ""
  ttl  = 90

  type  = "A"
  value = "127.0.0.1"
}
```

### Debug Output
https://gist.github.com/jbarreneche/78f6752aff380186fd0897c28a7d96f1

### Expected Behavior

An "A" record created at the top level domain

### Actual Behavior

Fail with 400 bad request. Probably the request in this case is malformed.

### Steps to Reproduce

1. `terraform apply` (with the dyn credentials and the above terraform file)

### Important Factoids

This also happens when trying to modify an existing record at that given level (this record were imported manually, and we wanted to change the TTL).

### PR DESCRIPTION
**Pull request by radeksimko**
Fixes #6

### Test results

```
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccDynRecord_Basic
--- PASS: TestAccDynRecord_Basic (12.65s)
=== RUN   TestAccDynRecord_noTTL
--- PASS: TestAccDynRecord_noTTL (12.24s)
=== RUN   TestAccDynRecord_Updated
--- FAIL: TestAccDynRecord_Updated (19.15s)
	testing.go:434: Step 1 error: Error applying: 1 error(s) occurred:

		* dyn_record.foobar: 1 error(s) occurred:

		* dyn_record.foobar: Failed to update Dyn record: server responded with 404 Not Found: {"status": "failure", "data": {}, "job_id": 4109885045, "msgs": [{"INFO": "id: You did not reference a specific record", "SOURCE": "BLL", "ERR_CD": "NOT_FOUND", "LVL": "ERROR"}, {"INFO": "update: No record updated", "SOURCE": "BLL", "ERR_CD": null, "LVL": "INFO"}]}
=== RUN   TestAccDynRecord_Multiple
--- PASS: TestAccDynRecord_Multiple (18.03s)
=== RUN   TestAccDynRecord_CNAME_trailingDot
--- PASS: TestAccDynRecord_CNAME_trailingDot (11.07s)
=== RUN   TestAccDynRecord_CNAME_topLevelDomain
--- PASS: TestAccDynRecord_CNAME_topLevelDomain (11.64s)
FAIL
exit status 1
FAIL	github.com/terraform-providers/terraform-provider-dyn/dyn	84.814s
make: *** [testacc] Error 1
```

The update test was broken before.

### CODE REVIEW

File: dyn/resource_dyn_record_test.go [hunk 1]
```diff
@@ -304,3 +328,12 @@ resource "dyn_record" "foobar" {
   type  = "CNAME"
   ttl   = 3600
 }`
+
+const testAccCheckDynRecordConfig_topLevelDomain = `
+resource "dyn_record" "foobar" {
+  zone = "%s"
+  name = ""
```
Comment (tombuildsstuff) [inline dyn/resource_dyn_record_test.go:335]: why not make this optional rather than Required?

**Review by tombuildsstuff — APPROVED** [review]
one minor comment - otherwise LGTM :)

File: dyn/resource_dyn_record_test.go (hunk 1 above)
Comment (radeksimko) [reply dyn/resource_dyn_record_test.go:335]: That is a good question 🤔  We probably could and should. Let me fix that.

Comment (tombuildsstuff) [reply dyn/resource_dyn_record_test.go:335]: now Name's optional - can we remove this line to ensure it works?

Comment (radeksimko) [reply dyn/resource_dyn_record_test.go:335]: sure, sorry for being trigger happy :)
